apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-gitops-flux-sops
  labels:
    app.kubernetes.io/name: spring-boot-k8s-gitops-flux-sops
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-boot-k8s-gitops-flux-sops
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-boot-k8s-gitops-flux-sops
    spec:
      containers:
        - name: spring-boot-k8s-gitops-flux-sops
          image: spring-boot-k8s-gitops-flux-sops:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/"
          volumeMounts:
            - name: application-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: application-config
          secret:
            secretName: spring-boot-k8s-gitops-flux-sops-config
            items:
              - key: application.yml
                path: application.yml
