apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-gitops-flux-sops-workshop
  labels:
    app.kubernetes.io/name: spring-boot-k8s-gitops-flux-sops-workshop
spec:
  selector:
    app.kubernetes.io/name: spring-boot-k8s-gitops-flux-sops-workshop
  ports:
    - name: http
      port: 80
      targetPort: 8080
