keys:
  flux_age_key: &flux_age_key age1xkr0q0wjnys2anw236xqqzwggqu2thxzgq56x7s0gz6nlewsvqpsf0nktc

creation_rules:
  - path_regex: secret\.enc\.yaml
    encrypted_regex: ^(data|stringData)
    age:
      - *flux_age_key
