apiVersion: v1
kind: Secret
metadata:
    name: spring-boot-k8s-gitops-flux-sops-config
type: Opaque
stringData:
    application.yml: ENC[AES256_GCM,data:JwwrIu/GRuspWColubfFHJvtgA7LLvttjuqtyxUmg4vQOGgrgC7YBVM+HAvlic+NcTAj0DeS1cSYdTiF6d+R3NoOCPg=,iv:vNYj8VV1feiVqZjhf1qcidgoUyfLkEkZ/QjQQDhDIB8=,tag:0vCHZLiF8jLVP0xyrnIAaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUmxSWS9BUzdadmk1NlFz
            SU5WeFVPeHQ3S3BPNytrQUNvUitoTFA0SGhBCk1EU1FWQkd3blY5L0k5Wis1d285
            R2wzbnBDSFVuT2cwNEk1djd2NEt3RlEKLS0tIE02cDZqb2U2ZDczQmxPL0o4cWp1
            NDh1ckIzNEZzTzN3VDl4THdtaWtuRzAKdh5v7Ck6dit4lufAMzm+/VO230MpmK0B
            Pe7miNN1r96vtRDS+EYOVlo6R9nwx24w1dYNMfLBAVezx7Wz4ifmGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7ku95y5vzu8v68zxemxtkzqptu8ghjk33zzjyqhej73dv0af6sznawlf
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-07-28T17:43:21Z"
    mac: ENC[AES256_GCM,data:Bs5/zYwfc9Yl1qj+tDGtL+B2E/FEdqdd0l66LxdNRm1Mq0aQt89BcbzZMdkiwKm7wmCZaVws7FYmBDFw05BxdwSya1soqMLHrPuEIiQu7leQhBk/WDtRTJRedNDN/3Fp86kzA/QVxWSwhox+LIVaF4NuxebIfZwowoHdphJ87cQ=,iv:CUKPaVYGiCpsQHF3uR9Lba10kqR/Gdi1kMPYVOJ21go=,tag:5ifOdnqglmfc62VhTHfqRw==,type:str]
    version: 3.13.3
