apiVersion: v1
kind: Secret
metadata:
    name: spring-boot-k8s-gitops-flux-sops-config
type: Opaque
stringData:
    application.yml: ENC[AES256_GCM,data:Z3xtxI/znV2jgiBQ2LaM+nRCzC0YDqB44YWy5BPpQ4vzx0Zxj4PKUKCBMwlww/kZ2e1cPwSPcdl+UU7JlHt37ck968k=,iv:SaRxZwSewVfpr/MRlrrUCDe5bbOnKp5WyiZax1OyuzM=,tag:3tkhnGP9k72PcbB1QMTrew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjakFyaktIMlNCR1FXN28v
            cFhyaHM4NHg3T3h5TGFtVnMyZXpNbWpjT0FBCldTOGdsWklSVHU3aXNrcXBwLzJH
            dmx5YWpsUVpRdTdyaFNMMGwwSUdHS1UKLS0tIGlKdGZSVXpXbkNiQVpBeWYyRC9W
            ZStkOTRUbzRHem5OQkQ4alB2eGV2TUUKHb6Pf1+D6ElpoBWckXWbOjAR+bcPOkCC
            MR5+1hYAUGJo4yq+EUfybP1BLZvCS2YURU5eL84T4Q/GgfNe5v1ekw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xkr0q0wjnys2anw236xqqzwggqu2thxzgq56x7s0gz6nlewsvqpsf0nktc
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-07-28T21:07:44Z"
    mac: ENC[AES256_GCM,data:WnDnynrSwbMP78I0fhKo7hzchK5FqgTVZBGHomqk7VT/qtW2zA5H5fSvEQCzfd1WGS93AUTNTnHke0DilUWe7PoG/ok8oQFSgWN0OCxY+kzYXgTxEEYxZ5PteMtHGopzVmS2d/vdeEEiwJepX9NJwpoq3iQiQqf4OfhP8IOORUA=,iv:wjBhDBQHTz6/6Dn07QvgLLo/2YP2eNK/qdF1d6HD6oM=,tag:MB6FEodt6ENwZ6/62ifi6Q==,type:str]
    version: 3.13.3
