apiVersion: v1
kind: Secret
metadata:
    name: spring-boot-k8s-gitops-flux-sops-config
type: Opaque
stringData:
    application.yml: ENC[AES256_GCM,data:Ei5hI0UAnVNgKFfXE+xx7Kqs9dHQ5Qapl/zzUjQA18Klogm/hIBYO2AWhrPpAOepL6fx2eKK6sJTK464Dd/qs+GZ,iv:I15Xb7hsx+0KvycJOC4PmTGeVAY33VGONdjw57vHlpc=,tag:aRinfLr4kl27O4h/iuzz2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWUVJblc5clNOOE1jVURl
            aVRWV01VUmZMYzRDREdiTTJ6ODJlZkZmSm40CmthYlpYZWFwNVJxYmdzcG01YjhH
            R243dTcwRlVHZzVtWWJadHZTaFA4N3MKLS0tIHowOUdxSGFuTU9nUkh6SDlMdjJQ
            OFdxdVJObFFzYkx4RmRGT1RrTmNLdVUKO3/M6oBfr9d/pgGGF3r1jHuJ2KTo6lT6
            qp6a31x6BGT5XYSZTwLOOpKUdYQgtbe8bh5aCdBcp5MMEH16Ut0Rxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dj7ku95y5vzu8v68zxemxtkzqptu8ghjk33zzjyqhej73dv0af6sznawlf
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-07-28T17:43:21Z"
    mac: ENC[AES256_GCM,data:5TLEQQxrAeMqKjp2yB3ZcINyonOBl/BSAtOByVj85oRdO6m4Ve1Ap2mUF1HCIkIjUDNe4rZriSSR6SEhUKly4aCz9ELGa0FbPDmrLOOwh2GwezeMGrZBu0toGZbtTvOQH95O3PNYTqzRW3TbcV1gItBqYWpkuCxOnjnnBIEZ0Vo=,iv:PgIq7kbCwFys2tdaLgMFjXXFK0QdSJr3v2YN3VRKRuc=,tag:R7mOp0LKozbGS8KNaNK4iA==,type:str]
    version: 3.13.3
