apiVersion: v1
kind: Secret
metadata:
    name: spring-boot-k8s-gitops-flux-sops-workshop-config
type: Opaque
stringData:
    application.yml: ENC[AES256_GCM,data:T8toSr8ja8/rHPceigA68e2IJdTzxyZy4FQqoELqdIAg9AS9wyVFz2UZIvu8CWLwYjPkkwhxdU6WCUPtO0TbHUAD,iv:jvxE/NgbS519AOMaS0pz/bp7jUR/i2Qs46X1yx6MdtQ=,tag:EladY1oH+LrEr3bAegkP9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSHdaL3RzRkVkNHB5N21n
            ZXdxd1llc01HZW1CYW5NTm8yNEVSTmsvd3hvClo4bG41M0VuYytLZzAvMVBLVEZI
            MldPbUdFa2FQUmlOdUVpRGNOc1VtZmMKLS0tIHpiT2VzckxGRmhOU0pITzA5T1J2
            R0pyTGVEUzRWei9xcHU3SXpoWStadlEKz+sZNu2dQ+6Z1bOQHjk8QyUbrsPeY32w
            eL93LfY+EyqAPw9oxyXLbgbn7GAGhUwJfyunb4k5t6R9+PZMYErPJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r2lsff8tazyxvqtvfz7ya5anv6rte75yrvk6nlc2yyaezq8433qephwvz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNkhETXRiWjJ3Wm5EbG12
            czM2dFpZdDFDUDE0dWNlNzlmNXFkRWlVOGc0Cm5ORi9GVG5LbDdicFRVcjk4T1Vz
            MDhWWUZNOERmYW9zQks2ZVBVSHRhNUUKLS0tIFB1TklyTHN5R3NsUG5DNFhieWgz
            Q1ozeTF1YjhwZ2EzUm0wWnJ2d3hiWFEKszSeYdy4WkOJIWlaPkjUAh4g0sM3dZkN
            o0U9Ps2HuFLRbkkLzc5+jj8oyAE8vrJ4g2Qo+RSQfn6HGWrLdbMYGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18qdpstfprlz0z52gn54qwkx7zzeryfsmps77w4rnhk73hf2shvvsp3xvrl
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-07-28T21:18:05Z"
    mac: ENC[AES256_GCM,data:QuOs9wGbHF42PVdYklpF8UinIJcXS82r5qnxU27dvDrXsgsAIyanZKJTz/4LwVI7FEPSFMCvtpuc0XrTLr2BsQQdo0t+wFBhH3HyMVv6o2Wi1TaeuTpG9o2QjanuPWxbWxUviP86DMbGhJ58IdnREiC5b/GNROnHhxVDxMPX6VE=,iv:vN8fr18dPjMeiCba1in0rxQRkvxRnd8ImQVEjlkhVz4=,tag:lXrYvfy/GoaZXEM6afCRng==,type:str]
    version: 3.13.3
