apiVersion: v1
kind: Secret
metadata:
    name: spring-boot-k8s-gitops-flux-sops-config
type: Opaque
stringData:
    application.yml: ENC[AES256_GCM,data:1VIfwh16WhMCIHiMG7lA8wC1fuu2e36Va1KqPfteaG5m5Ts1S1rJdEou63LUcC8ISAlbE8nDP7geK5ncjpwg5NBZ,iv:uozQqd1lbjyTLM2sSQL5kPM6kOhALL8K+z0NIHlamRs=,tag:I39ag6XkTUpiFRp6DIf1GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZnNmeWtqZkZoeTg2OFBu
            RVlxczJ6Q2tiRktreXBGRVBGbFc4aTY4UjNvClZtdGVvY2h2eWNOdCs2YjJmVGVo
            RVVoRTdlVlpuNGhtOFZNbGkxdG5CMzgKLS0tIHZ6Tnd4VzNBQlVYYURWNHJTUUl4
            cWppRXVIa2Z4cDAvVkU5cjhJcyttb1kKpzQmFtglNpvRi3undx6JykikNOWPaA5G
            wKK1W2oQAesMD9cFPBYAICyaRmcisVA/GCB2/97kQIJh7BeMv6+91w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r2lsff8tazyxvqtvfz7ya5anv6rte75yrvk6nlc2yyaezq8433qephwvz
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-07-28T21:07:44Z"
    mac: ENC[AES256_GCM,data:SilwQItuGLd2nv2CtO27VEpbAPXaTeVnTES9qoc3Eav5hx2tova+rgfy+bbM5cjIrDD/8kEwBPO8RY3QAw5PM9+PA9kb/SKwlO1XaTkde+TWwgYKQM2akMXFD7tGO3C2O9pdh6UqQTKqZHGJsDcKNRaFU+LReIgQ5Ivjpz+xijo=,iv:uPC8dusb8R/Vaz53a4z3dp7+fxRRQhr/lx/NZirqhbw=,tag:GaDpcCjsdAHpKCj6dqTT7w==,type:str]
    version: 3.13.3
